# fly.toml app configuration file generated for elysia-app on 2023-10-01T12:06:55+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elysia-app"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
