# fly.toml app configuration file generated for elysia-demo-app on 2023-12-22T21:10:32+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elysia-demo-app"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
