name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.4.0
      - uses: actions/setup-python@v5.6.0
      - uses: pre-commit/action@v3.0.1
